# Ansible playbook to run a 
--- 
- name: Install python3, docker and docker-compose
  hosts: docker_server
  gather_facts: no
  become: yes
  tasks:
    - name: Install python3, docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        state: present 
        update_cache: yes

    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{lookup('pipe','uname -s')}}-{{lookup('pipe','uname -m')}}"
        dest: /usr/local/bin/docker-compose
        mode: +x
  
    - name: Install python depenency for docker and docker compose
      pip:
        name:
          - docker
          - docker-compose
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  roles:
    - create_user

- name: Start nginx container
  hosts: docker_server
  roles:
    - start_container
